# Generated by Django 5.2.8 on 2025-12-02 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0002_alter_model_name'),
        ('sections', '0002_alter_section_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('measurement_date', models.DateField()),
                ('calibration_date', models.DateField()),
                ('clean_date', models.DateField()),
                ('calibrated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibrated_scales', to=settings.AUTH_USER_MODEL)),
                ('cleaned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaned_scales', to=settings.AUTH_USER_MODEL)),
                ('measured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measured_scales', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scales', to='models.model')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scales', to='sections.section')),
            ],
        ),
    ]
