# Generated by Django 6.0 on 2025-12-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('FRL', 'Frente de Loja'), ('ACO', 'Açougue'), ('PEI', 'Peixaria'), ('FRI', 'Frios e Laticinios'), ('PAD', 'Padaria'), ('HOR', 'Hortifrúti'), ('DOC', 'Docas Secas'), ('DOCF', 'Docas Frias')], max_length=100),
        ),
    ]
